# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b38cb28a2fb6c2a3047811817d2c3dbfb0d32449c059f4d5afb35e7b1d1a338e706981468352a17c55bd682f9718647a38c974ac8a5cc73cbc0dc16d1005257

test:
  secret_key_base: ca8e5012370c23b374564fb31ec37163b10e52255e156eee93bf2208ca2ebdf5c5245ff746b00f82a9fcc1ce73cd22cb5fa3a17b2281e85a72892179e80e25da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
